### PR TITLE
Revert "Display list of item at the homepage"

### PR DESCRIPTION
**Pull request by tugsem**
Reverts RWUBAKWANAYO/Module2-Capstone-Project#23

### CODE REVIEW

**Review by tugsem — COMMENTED** [review]
Hello @RWUBAKWANAYO, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

Alt Text
## Highlights
You made good job so far 
✅ You created list from chosen API
✅ You use GitFlow correct
✅ No linters errors

## Required Changes ♻️ 

 Kindly check comments with the [Required] prefix below, which addressing the issues:

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by tugsem** [comment]
image

- [ ] [Requested] Please fix this list view by adding media queries to your CSS file. This will make it more responsive. You can add { flex-direction: column} in small screens

**Comment by tugsem** [comment]
image
- [ ] [Requested] Please remove these commas at the end of the list elements to make it more aesthetic and professional.

**Comment by tugsem** [comment]
- [ ] [Requested] Please remove extra list items on the page (6 items will be enough as in the wireframe: 

image
)

**Comment by RWUBAKWANAYO** [comment]
Hello @tugsem, 
I solved the issues and let me know what you think about the changes

**Pull request closed without merging**
